config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :planets, only: [:show] do
    resources :aliens, only: [:new, :create]
  end
  resources :aliens, only: [:destroy] do
    resources :mutations, only: [:new, :create]
  end
end


# planets#show -> /planets/:id
# aliens#new    ->  planets/:planet_id/aliens/new
# aliens#create ->  planets/:planet_id/aliens
# aliens#destroy -> /aliens/:id


# mutations#new -> aliens/:alien_id/mutations/new
# mutations#create -> aliens/:alien_id/mutations

app/models/alien.rb
class Alien < ApplicationRecord
  belongs_to :planet # alien.planet
  has_many :mutations, dependent: :destroy
  has_many :powers, through: :mutations   # yann.powers
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo # alien.photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mutation.rb
class Mutation < ApplicationRecord
  belongs_to :alien
  belongs_to :power
  validates :power, uniqueness: { scope: :alien }
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :aliens, dependent: :destroy # planet.aliens
  validates :name, presence: true
end

app/models/power.rb
class Power < ApplicationRecord
  has_many :mutations
  has_many :aliens, through: :mutations
  # has_many :planets, through: :aliens   -> power.planets
  validates :name, presence: true, uniqueness: true
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController

  def new
    # this is for the NESTED form
    @planet = Planet.find(params[:planet_id])
    @alien = Alien.new
  end

  def create
    @planet = Planet.find(params[:planet_id])
    @alien = Alien.new(alien_params)
    @alien.planet = @planet
    if @alien.save
      redirect_to planet_path(@planet)
    else
      # 'show the new.html.erb view with the @alien that we just tried to create'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @alien = Alien.find(params[:id])
    @alien.destroy
    redirect_to planet_path(@alien.planet)
  end

  private

  def alien_params
    params.require(:alien).permit(:name, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mutations_controller.rb
class MutationsController < ApplicationController

  def new
    @alien = Alien.find(params[:alien_id])
    @mutation = Mutation.new
    # all the powers our alien has:
    # @powers = @alien.powers
    # all the powers our alien DOESNT have:
    @powers = Power.where.not(id: @alien.powers).order(name: :asc)
  end

  def create
    @alien = Alien.find(params[:alien_id])
    @mutation = Mutation.new(mutation_params)
    @mutation.alien = @alien
    if @mutation.save
      redirect_to planet_path(@alien.planet)
    else
      @powers = Power.where.not(id: @alien.powers).order(name: :asc)
      # just shows new.html.erb (it does not run the controller action new)
      render :new, status: :unprocessable_entity
    end
  end

  private

  def mutation_params
    params.require(:mutation).permit(:power_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @planets = Planet.order(name: :asc)
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  def show
    @planet = Planet.find(params[:id])
  end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mutations_helper.rb
module MutationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/aliens/new.html.erb
<div class="container mt-3">
  <h1>Add Alien to <%= @planet.name %></h1>
  <%= simple_form_for [@planet, @alien] do |f| %>
    <%= f.input :name %>
    <%# This is the old way w/a string url %>
    <%#= f.input :image_url %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Submit', class: 'btn btn-danger mt-2' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galaxy1105</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/mutations/new.html.erb
<div class="container mt-3">
  <h1>Add Power</h1>
  <%= simple_form_for [@alien, @mutation] do |f| %>
    <%= f.association :power, include_blank: false, collection: @powers %>
    <%= f.submit 'Submit', class: 'btn btn-danger mt-2' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://d18lkz4dllo6v2.cloudfront.net/cumulus_uploads/entry/43959/adobe-aliens.jpeg);">
  <div class="container">
    <h1>Galaxy 1105</h1>
  </div>
</div>
<div class="container my-5">
  <div class="cards">
    <% @planets.each do |planet| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= planet.banner_url %>)">
        <%= planet.name %>
        <%= link_to '', planet_path(planet), class: 'card-category-link'%>
      </div>
    <% end %>
  </div>
</div>

app/views/planets/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @planet.banner_url %>);">
  <div class="container">
    <h1><%= @planet.name %></h1>
    <%= link_to 'Add Alien', new_planet_alien_path(@planet), class: 'btn btn-danger mt-2'  %>
  </div>
</div>
<%# image tag -> it + tab%>
<%# cloudinary image tag -> it + tab%>
<div class="container my-4">
  <div class="cards">
    <% @planet.aliens.each do |alien| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= alien.photo.attached? ? cl_image_path(alien.photo.key) : alien.image_url %>)">
        <%= alien.name %>
        <div class="card-tags">
          <% alien.powers.each do |power| %>
            <span><%= power.name %></span>
          <% end %>
        </div>
        <%= link_to alien_path(alien), class: 'card-remove-link', data: { turbo_method: :delete, turbo_confirm: "Exterminate #{alien.name}?" } do %>
          <i class="fa-solid fa-skull"></i>
        <% end %>
        <%= link_to new_alien_mutation_path(alien), class: 'card-add-link' do %>
          <i class="fa-solid fa-dna"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>